version: '3.5'

volumes:
  mysql-data:
    driver: local
  bundle_install:
    driver: local
  bundle:
    driver: local
  node_modules:
    driver: local

services:

### Workspace ############################################
  workspace: &app_base
    build:
      context: ./docker/web
    command: ["tail", "-F", "/dev/null"]
    volumes:
      - .:/app:cached
      - bundle_install:/app/vendor/bundle
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
    environment:
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - mysql
    tty: true
    stdin_open: true

### Rails ###############################################
  rails:
    <<: *app_base
    command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]
    ports:
      - 3000:3000

### Sidekiq ##############################################
  sidekiq:
    <<: *app_base
    command: ["bundle", "exec", "sidekiq"]
    ports: []
    depends_on:
      - mysql
      - redis

### MySQL ################################################
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3307:3306

### Redis ################################################
  redis:
    image: redis:3.2.12-alpine
    ports:
      - 6379:6379
