#!/bin/bash

if test "$1" = ""; then
  echo "Usage: ./attach <container_name>"
  exit 1
fi

CONTAINER_NAME=$1
CONTAINER_ID=`docker ps | grep -- "-${CONTAINER_NAME}\s" | awk '{print $1}'`

if test "$CONTAINER_ID" = ""; then
  echo "No container found"
  exit 1
fi

echo "Attaching $CONTAINER_ID"
echo "Press Ctrl+P, Ctrl+Q to detach"

docker attach $CONTAINER_ID
